version: '3'

services:
 elasticsearch:
   image: elasticsearch:6.8.10
   networks:
    - loging
   volumes:
      - esdata:/usr/share/elasticsearch/data

 kibana:
  image: kibana:6.8.10
  ports:
    - 5601:5601
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  networks:
    - loging
  depends_on:
    - elasticsearch

volumes:
  esdata:
    driver: local

networks:
  loging:
    driver: bridge